name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Checkout code
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - name: Deploy mkdocs
        env:
          MKDOCS_CHATBOT_ID: ${{ secrets.CHATBOT_ID }}
          ANALYTICS_GOOGLE_ID: ${{ secrets.ANALYTICS_GOOGLE_ID }}
        run: mkdocs gh-deploy --force

      - name: Deploy to GitHub Pages
        run: echo 'www.blog.celestialcode.us.kg' > CNAME